# Generated by Django 5.2.4 on 2025-08-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='monthly_salary',
            new_name='monthly_income',
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
