# Generated by Django 5.2.4 on 2025-08-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_api', '0002_rename_monthly_salary_customer_monthly_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='current_debt',
        ),
    ]
